### PR TITLE
Upgrade Laravel 10

### PR DESCRIPTION
**Pull request by mtawil**

### CODE REVIEW

**Comment by mtawil** [comment]
@atymic Please merge this

**Comment by mtawil** [comment]
@freekmurze @mpociot @mdrost @themsaid @atymic Anyone can help here, please?

**Comment by pxlrbt** [comment]
@atymic Any chance this can be merged?

**Review by atymic — APPROVED** [review]

**Comment by pxlrbt** [comment]
Thanks!

**Pull request merged**
