### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/smsapi.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-notification-channels/smsapi": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by opheus2** [comment]
@dwightwatson can we merge this too 🙏🏿

**Comment by dwightwatson** [comment]
I'm not a maintainer on this repo, sorry

**Comment by opheus2** [comment]
@mtawil can we merge this 🙏🏿

**Comment by hoRacy** [comment]
Forks are ready to be merged :) Please @atymic @mtawil for help!

**Comment by psafarov** [comment]
`smsapi/php-client` 3.0 is not supported, somebody has to port it, before it can be merged :(

**Comment by hoRacy** [comment]
> `smsapi/php-client` 3.0 is not supported, somebody has to port it, before it can be merged :(

This package use smsapi/php-client 1.8.* which is still compatible with Laravel 11. Is there really a need for a port to version smsapi/php-client 3.0?

**Comment by hoRacy** [comment]
Hi @atymic 
https://laravel-notification-channels.com/smsapi/ - according to the documentation you are responsible for maintaining this project. Please merge this pull request as the package is not compatible with Laravel 11. 
If this is not possible, please give us information what to do next.
Best regards

**Comment by psafarov** [comment]
@atymic `smsapi/php-client` version should've stayed unchanged, the newest version 3.0 is not supported.

**Pull request merged**
